development:
  adapter: mysql2
  host: localhost
  username: root
  password:
  reconnect: true
  database: finance_development
test:
  adapter: mysql2
  host: localhost
  username: root
  password:
  reconnect: true
  database: finance_development
production:
  adapter: mysql2
  host: localhost
  username: root
  password:
  reconnect: true
  database: finance_development